import type { Metadata } from "next";
import "@/app/globals.css";
import { RootClient } from "./_components/RootClient";
import { inter } from "./ui/font";

export const metadata: Metadata = {
  title: "Kento Honda - New Portfolio Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="scroll-smooth" lang="en">
      <body className={inter.className}>
        <RootClient>{children}</RootClient>
      </body>
    </html>
  );
}
