import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import { RootClient } from "./_components/RootClient";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Kento Honda - New Portfolio Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="scroll-smooth" lang="en">
      <body className={inter.className}>
        <RootClient>{children}</RootClient>
      </body>
    </html>
  );
}
